name: Split and Commit File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # ทำงานทุกวันตอนเที่ยงคืน

jobs:
  split_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download file
        run: |
          curl -o inbound.txt https://raw.githubusercontent.com/bitwire-it/ipblocklist/refs/heads/main/inbound.txt

      - name: Split and commit
        run: |
          mkdir -p output
          split -l 50000 inbound.txt output/part_

      - name: Commit files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Add new parts from inbound.txt" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
